language: generic
sudo: required
services:
  - docker
before_install:
  - docker pull rakudo-star
  - docker run rakudo-star perl6 -v
script:
  - |
    docker run -v $PWD:/$TRAVIS_REPO_SLUG -it -w /$TRAVIS_REPO_SLUG rakudo-star bash -c '
    set -ex
    zef install --deps-only --/test .
    PERL6LIB=$PWD/lib prove -e perl6 -vr t/
    '
