name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        raku-version:
          - '2020.06'

    steps:
      - uses: actions/checkout@v2
      - name: Install Rakudo
        run: |
          url=$(curl -fsSL https://rakudo.org/dl/rakudo | jq -r '[. | sort_by(.build_rev) | reverse | .[] | select(.ver == "${{ matrix.raku-version }}" and .format == "tar.gz" and .arch == "x86_64" and .platform == "linux") | .url][0]')
          [[ $url = null ]] && printf '::error::Failed to find url for ${{ matrix.raku-version }}\n\n' && exit 1
          curl -fsSL $url | tar xzf - -C $HOME
          printf "::add-path::$HOME/.raku/bin:$HOME/rakudo-${{ matrix.raku-version }}/share/perl6/site/bin:$HOME/rakudo-${{ matrix.raku-version }}/bin\n"
      - name: raku -V
        run: raku -V
      - name: Install Dependencies
        run: |
          zef install --deps-only --/test .
          zef install --/test App::Prove6
      - name: Run Tests
        run: prove6 -l t
